name: Swift

on:
  push:
    branches: [ master ]
    
jobs:
  build-dev: 

    runs-on: macos-latest
    env:
      XC_VERSION: ${{ '12.1' }}
      XC_PROJECT: ${{ '.xcodeproj' }}
      XC_SCHEME: ${{ 'CICDExample' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Create Folder for certificates and profiles
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        mkdir -p ~/Library/MobileDevice/Certificates/
    - name: Get Certificate
      id: certFileDecode
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'certificate.p12'
        encodedString: ${{ secrets.P12_BASE64 }}
    - name: Copy Certificate
      run: mv ${{ steps.certFileDecode.outputs.filePath }} ~/Library/MobileDevice/Certificates/certificate.p12
    - name: Get Profile
      id: profFileDecode
      uses: timheuer/base64-to-file@v1.0.3
      with:
        fileName: 'decoded.mobileprovision'
        encodedString: ${{ secrets.MOBILEPROVISION_BASE64 }}
    - name: Copy Profiles
      run: mv ${{ steps.profFileDecode.outputs.filePath }} ~/Library/MobileDevice/Provisioning\ Profiles/decoded.mobileprovision
    - name: Install python dependencies
      run:  python3 -m pip install codemagic-cli-tools
    - name: Initialize Keychain with certificate
      run: |
        keychain initialize
        keychain add-certificates --certificate ~/Library/MobileDevice/Certificates/certificate.p12 --certificate-password ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: Build archive
      run: |  
        xcodebuild -project "$XC_PROJECT" -configuration Release -scheme "$XC_SCHEME" -derivedDataPath DerivedData -archivePath DerivedData/Archive/CICDExample archive
    - name: Export Archive
      run: |
        xcodebuild -exportArchive -archivePath DerivedData/Archive/CICDExample.xcarchive -exportOptionsPlist provisioning/App-Store.plist -exportPath DerivedData/ipa
